# -*- coding: utf-8 -*-
"""Ejercicio2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQJw5yV7bE9HgFmQDvgj6KJgnuMR8tjk
"""

A = 10

A1 = 33

print("Valor de A:", A)

print("Valor de A1:", A1)