# -*- coding: utf-8 -*-
"""Ejercicio6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6gQxl1SEa4WHSU5ODAzM8Lp3z6xmjcC
"""

contador = 1

while contador <= 10:
    print(contador)
    contador = contador + 1