# -*- coding: utf-8 -*-
"""Ejercicio11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ChRMkNEfj_EeM_wozhgpf6-W6q7wk5Ch
"""

numero = int(input("Ingrese un número: "))

if numero % 2 == 0:
    print("El número es par")
else:
    print("El número es impar")