# -*- coding: utf-8 -*-
"""Ejercicio7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vAgL9k9QeP00W_H4A6tOMPWy2D6GL2Z
"""

contador = 0

while contador <= 60:
    print(contador)
    contador = contador + 2

resultado = contador / 2

print("Resultado dividido por 2:", resultado)