# -*- coding: utf-8 -*-
"""Ejercicio9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTMziYyAsGKucCzO-E9MjgeNvrxW2KZm
"""

contador = 1
cantidad = 0

while contador <= 100:

    if contador % 2 != 0:
        print(contador)
        cantidad = cantidad + 1

    contador = contador + 1

print("Cantidad de impares:", cantidad)