# -*- coding: utf-8 -*-
"""Ejercicio5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nBvGVIwYeMVXgDmrTIjzEL5b87bYqEa
"""

A = 1
A1 = 1

while A != 0 or A1 != 0:

    A = int(input("Ingrese el valor de A: "))
    A1 = int(input("Ingrese el valor de A1: "))

    suma = A + A1

    print("La suma es:", suma)