# -*- coding: utf-8 -*-
"""Ejercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyAKW-kG8spY-UCwq8sjjrFImAzNT4BL
"""

A = int(input("Ingrese el valor de A: "))
A1 = int(input("Ingrese el valor de A1: "))

suma = A + A1

print("La suma es:", suma)