# -*- coding: utf-8 -*-
"""Ejercicio10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114Mwa0V6U5HYV9IKvDL2T6Ajpmw1ViEZ
"""

numero = int(input("Ingrese un número: "))

if numero > 0:
    print("El número es positivo")

if numero < 0:
    print("El número es negativo")

if numero == 0:
    print("El número es cero")