# -*- coding: utf-8 -*-
"""Ejercicio13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUsZ_vGIKLD6XVy2U826gTSlvFQwihDs
"""

numero1 = int(input("Ingrese el primer número: "))
numero2 = int(input("Ingrese el segundo número: "))
numero3 = int(input("Ingrese el tercer número: "))
numero4 = int(input("Ingrese el cuarto número: "))
numero5 = int(input("Ingrese el quinto número: "))

mayor = numero1
menor = numero1

if numero2 > mayor:
    mayor = numero2

if numero3 > mayor:
    mayor = numero3

if numero4 > mayor:
    mayor = numero4

if numero5 > mayor:
    mayor = numero5

if numero2 < menor:
    menor = numero2

if numero3 < menor:
    menor = numero3

if numero4 < menor:
    menor = numero4

if numero5 < menor:
    menor = numero5

print("El número mayor es:", mayor)
print("El número menor es:", menor)