# -*- coding: utf-8 -*-
"""Ejercicio14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-LNKBE9-lr6e7DfpYGdlKZxg3qF2MUl
"""

frase = input("Ingrese una frase: ")
letra = input("Ingrese una letra: ")

contador = 0

for caracter in frase:

    if caracter == letra:
        contador = contador + 1

print("La letra aparece", contador, "veces")