# -*- coding: utf-8 -*-
"""Ejercicio8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wU4Ha46-tafMxCl8v52c3bWTtsVExdey
"""

contador = 100

while contador >= 0:
    print(contador)
    contador = contador - 1