# -*- coding: utf-8 -*-
"""Ejercicio3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5lTtAqCzp0RSoIS1xXeNtFfHq6eO-B-
"""

A = 10
A1 = 33

suma = A + A1

print("La suma es:", suma)